version: '2'
services:
  election_service:
    build: .
    ports: 
      - "8081:8081"
    depends_on:
      - mysql
      - redis
    command: "npm start"
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: election
